server:
  addr: ":8081"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 20s

routes:
  - path_prefix: "/users"
    strategy: round_robin
    timeout: 3s
    health_check:
      path: "/"
      interval: 2s
      timeout: 1s
      healthy_threshold: 2
      unhealthy_threshold: 2
    upstreams:
      - url: "http://localhost:9001"
        weight: 1
      - url: "http://localhost:9002"
        weight: 1
